#variable - a container for storing  a value(string, integer,float,boolean..)
#f string

#Strings 
name="ashi"
print(f"hello{name}")

#integers
first=20
second = 15
print(f"first prize is {first},second prize is {second}")

#float n= 3.5
price=10.99
print(f"price is {price}")

#boolean true or false

is_student= True
if is_student:
    print("you are a student")
else:
    print("you are a student")

for_sale = False
if for_sale:
    print("for sale")
else:
    print("not for sale")